version: '4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/test
      - PORT=3000
    volumes:
      - .:/app
    depends_on:
      - mongodb

volumes:
  mongo-data: