version: 2.1

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cicleci/node:20 # use the default executor defined within the orb
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      # - deploy:
      #     requires:
      #       - build_and_test