name: Deploy to AWS ECS

on:
  workflow_run:
    workflows: ["Build and Push to AWS ECR"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Environment Variables
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my_node_app  # Change to your ECR repository name
          IMAGE_TAG: latest
          ECS_CLUSTER: node-app-cluster  # Change to your ECS cluster name
          ECS_SERVICE: my-ecs-service  # Change to your ECS service name
          ECS_TASK_DEFINITION: my-task-definition  # Change if needed
        run: echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Update ECS Task Definition
        id: task-def
        run: |
          aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION --query taskDefinition > task-def.json
          
          NEW_TASK_DEF=$(jq --arg IMAGE "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" '.containerDefinitions[0].image=$IMAGE' task-def.json)
          
          echo "$NEW_TASK_DEF" > new-task-def.json
          
          TASK_REVISION=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)
          
          echo "TASK_REVISION=$TASK_REVISION" >> $GITHUB_ENV

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition $TASK_REVISION
